name: galactic-spin 
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - numpy
  - scipy
  - matplotlib
  - mpld3
  - h5py
  - sympy
  - ipympl
  - ipywidgets==7.6.5
  - ffmpeg
  - jupyterlab
  - lmfit
